version: '3.4'

services:
  dockernginxts: # <SERVICE-NAME>
    image: docker-nginx-ts # <IMAGE-NAME>
    container_name: docker-nginx-ts # <CONTAINER-NAME>
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
